RED = 0
BLUE = 1
GREEN = 2
DARK = 3

ML_PER_BOTTLE = 100

POTIONS_PER_CAPACITY_POINT = 50
ML_PER_CAPACITY_POINT = 10_000

INVENTORY_ID = 1


POTION_FIRST_NAMES = [
    "Ancient",
    "Angry",
    "Assassin's",
    "Astounding",
    "Balm of",
    "Blessed",
    "Brew of",
    "Broth of",
    "Caramel",
    "Assassin's",
    "Broth of",
    "Cocktail of",
    "Concoction of",
    "Container of",
    "Cosmic",
    "Cultivated",
    "Cure",
    "Deep",
    "Deep",
    "Demonic",
    "Demonic",
    "Demonic",
    "Demonic",
    "Devilish",
    "Devil" "s",
    "Dragon" "s",
    "Draught of",
    "Draught of",
    "Drink of",
    "Elixir of",
    "Elixir of",
    "Elixir of",
    "Elixir of",
    "Elixir of",
    "Elixir of",
    "Elixir of",
    "Emerald",
    "Fatal",
    "Famous",
    "Fatal",
    "Fatal",
    "Fatal",
    "Flagship of",
    "Flask of",
    "Glorious",
    "Glowing",
    "Hide from",
    "High",
    "Wine of",
    "Infinite",
    "Infinite",
    "Lord's",
    "Messenger's",
    "Magic",
    "Mint",
    "Mutton",
    "Nectar of",
    "Oil of",
    "Drink of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Potion of",
    "Protection against",
    "Protection against",
    "Ruby",
    "Speedy",
    "Tea of",
    "Tea of",
    "Tea of",
    "Star-Eyed",
    "Torch of",
    "Vial of",
    "White",
    "Wicked",
    "Vial of",
    "Wild Boar",
    "Wine of",
]

POTION_SECOND_NAMES = [
    "Arctic",
    "Sea",
    "Despair",
    "Irrational Light",
    "Failed Flight",
    "Sight",
    "River",
    "Experience",
    "Fire Protection",
    "Fog Breathing",
    "Mystery",
    "Wizardry",
    "Far Sight",
    "Hyperness",
    "Brew",
    "Blend",
    "Itch",
    "Cordial",
    "Shot",
    "Azure Orange",
    "Lemon Potion",
    "Pleasant Coconut",
    "Water",
    "Jailer",
    "Water",
    "Breath",
    "the Muses",
    "the Third Child",
    "the Ballard's",
    "Diplomacy",
    "Intelligence",
    "Legend",
    "Parrot Form",
    "Stargazing",
    "the Fallen",
    "the Fates",
    "the North",
    "the Unknown",
    "Vulnerability",
    "Rain",
    "Body Part",
    "Foul Apple",
    "Purple Fisherman",
    "Squirt",
    "Tea",
    "the North",
    "the Purple Troubadour",
    "Incumbent",
    "Eyes",
    "from Death",
    "Dishonorable Draught",
    "of Thinking",
    "Liqueur Draught",
    "Tea",
    "Delight",
    "Voice",
    "Sadness",
    "Shot",
    "Broth",
    "Intelligence",
    "Greater Thirst",
    "Blindness",
    "Acid",
    "Climbing",
    "Delayed Reaction",
    "Encoding",
    "Enhanced Vocals",
    "Fake Death",
    "Free Knowledge",
    "Creation",
    "Infinite Limes",
    "Learning Sciences",
    "Mana Infusion",
    "Protection against Terror",
    "Tea",
    "Random Health",
    "Rapid Disintegration",
    "Sight beyond Sight",
    "Stargazing",
    "Sweetbread",
    "the Deputy",
    "the Spoken Word",
    "the Warlord",
    "Thirst",
    "Undoing",
    "against Lightning",
    "against Squirrels",
    "Rascal",
    "Moss",
    "Distraction",
    "Exploding",
    "Soothing",
    "Surprising",
    "the Moon",
    "Unspeakable Terror",
    "Outlaw",
    "Punch",
    "Terror",
    "Boar Wine",
    "Armour",
]
